# Generated by Django 5.0 on 2023-12-21 14:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userselection_usersubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='id',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
