# Generated by Django 5.0 on 2023-12-21 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_usersubmission_id_usersubmission_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselection',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='user',
        ),
        migrations.CreateModel(
            name='UserQuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
        migrations.DeleteModel(
            name='UserSelection',
        ),
        migrations.DeleteModel(
            name='UserSubmission',
        ),
    ]
