# Generated by Django 5.0 on 2023-12-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_userselection_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizscore',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
